"""Redshift-to-Snowflake mapping and conservative DDL generation."""

from __future__ import annotations

from typing import Iterable, Optional


TYPE_MAP = {
    "smallint": ("SMALLINT", "AUTO"),
    "integer": ("INTEGER", "AUTO"),
    "int": ("INTEGER", "AUTO"),
    "bigint": ("BIGINT", "AUTO"),
    "real": ("FLOAT", "REVIEW"),
    "double precision": ("DOUBLE", "REVIEW"),
    "double": ("DOUBLE", "REVIEW"),
    "boolean": ("BOOLEAN", "AUTO"),
    "date": ("DATE", "AUTO"),
    "timestamp": ("TIMESTAMP_NTZ", "REVIEW"),
    "timestamp without time zone": ("TIMESTAMP_NTZ", "REVIEW"),
    "timestamp with time zone": ("TIMESTAMP_TZ", "REVIEW"),
    "timestamptz": ("TIMESTAMP_TZ", "REVIEW"),
    "super": ("VARIANT", "REVIEW"),
    "geometry": ("GEOMETRY", "REVIEW"),
    "geography": ("GEOGRAPHY", "REVIEW"),
}


def map_type(column: dict) -> dict:
    source = str(column.get("data_type", column.get("type", ""))).lower().strip()
    if source in {"numeric", "decimal"}:
        precision = column.get("numeric_precision") or column.get("precision")
        scale = column.get("numeric_scale") or column.get("scale")
        target = f"NUMBER({precision},{scale})" if precision is not None and scale is not None else "NUMBER"
        status = "AUTO" if precision is not None and scale is not None else "REVIEW"
    elif source in {"character varying", "varchar", "nvarchar", "text"}:
        length = column.get("character_maximum_length") or column.get("length")
        target = f"VARCHAR({length})" if length else "VARCHAR"
        status = "AUTO" if length else "REVIEW"
    elif source in {"character", "char"}:
        length = column.get("character_maximum_length") or column.get("length")
        target = f"CHAR({length})" if length else "CHAR"
        status = "REVIEW"
    else:
        target, status = TYPE_MAP.get(source, ("VARCHAR", "UNSUPPORTED"))
    return {"source_type": source, "target_type": target, "status": status, "column": column.get("column_name", column.get("name"))}


def manifest(summary: dict, catalog: Optional[dict] = None, target: Optional[dict] = None) -> dict:
    target = target or {}
    catalog_columns = catalog.get("columns", []) if isinstance(catalog, dict) else []
    grouped = {}
    for column in catalog_columns:
        key = (column.get("table_schema", column.get("schema", "")), column.get("table_name", column.get("table", "")))
        grouped.setdefault(key, []).append(column)
    tables = []
    for item in summary.get("source_tables", []):
        if item.get("source_system") != "redshift":
            continue
        parts = str(item.get("name", "")).split(".")
        schema = parts[-2] if len(parts) > 1 else "public"
        table = parts[-1]
        target_schema = target.get("schema", "QLIK_STAGE")
        target_table = table.upper()
        columns = grouped.get((schema, table), []) or grouped.get((schema.lower(), table.lower()), [])
        mappings = [map_type(column) for column in columns]
        tables.append({
            "source_system": "redshift",
            "source_schema": schema,
            "source_table": table,
            "target_database": target.get("database", ""),
            "target_schema": target_schema,
            "target_table": target_table,
            "strategy": "replicate_raw_table",
            "columns": mappings,
            "status": "ready_for_mapping" if columns else "catalog_required_for_ddl",
        })
    return {"schema_version": 1, "tables": tables}


def ddl(manifest_data: dict) -> str:
    statements = ["-- Generated by qlik-redshift-lineage. Review every REVIEW/UNSUPPORTED mapping.", ""]
    for item in manifest_data.get("tables", []):
        if not item.get("columns"):
            statements.append(f"-- SKIPPED {item['source_schema']}.{item['source_table']}: catalog metadata was not supplied.")
            continue
        database = f"{item['target_database']}." if item.get("target_database") else ""
        columns = []
        for column in item["columns"]:
            marker = f" -- {column['status']} from {column['source_type']}"
            columns.append(f"  {column['column']} {column['target_type']}{marker}")
        statements.append(f"CREATE TABLE IF NOT EXISTS {database}{item['target_schema']}.{item['target_table']} (\n" + ",\n".join(columns) + "\n);")
        statements.append("")
    return "\n".join(statements).rstrip() + "\n"
